#ifndef _RJONE_ERR_H_
#define _RJONE_ERR_H_

#ifdef __cplusplus
extern "C" {
#endif



#define RJONE_BUF_LEN_NOT_ENOUGH 			(-1000)   
#define RJONE_NOT_SUPPORT_CHIP				(-1001)
#define RJONE_UNKNOW_SENSOR_CHIP				(-1002)
#define RJONE_INPUT_PARAM_ERR					(-1003)
#define RJONE_MORE_THAN_MAX_MEDIA_NUM		(-1004)
#define RJONE_DEV_INIT_ERR						(-1005)
#define RJONE_MEDIA_SYS_NOT_INIT				(-1006)
#define RJONE_UNKNOW_ERR						(-1007)
#define RJONE_NOT_CREATE_JPEG_SNAP_MEDIA	(-1008)
#define RJONE_OP_TIME_OUT						(-1009)
#define RJONE_NOT_CREATE_AUDIO_MEDIA			(-1010)
#define RJONE_WORNG_MEDIA_ID					(-1011)
#define RJONE_MEM_MALLOC_ERR					(-1012)
#define RJONE_NULL_PTR_ERR						(-1013)
#define RJONE_NOT_SUPPORT_FUNC_ERR			(-1014)



#define  RJONE_ERR_NO_DEV  				(-2000)
#define  RJONE_ERR_GPIO_ID		    				(-2001)
#define  RJONE_ERR_GPIO_WORK_MODE		    	(-2002)



#define  RJONE_NET_MODE_CHECK_FLAG_ERR		(-3000)
#define  RJONE_NET_MODE_ALREADY_OPEN_ERR	(-3001)
#define  RJONE_NET_MODE_CONNECT_ERR			(-3002)
#define  RJONE_NET_MODE_SET_SOCKET_ERR		(-3003)
#define  RJONE_NET_MODE_ACCEPT_ERR			(-3004)
#define  RJONE_NET_MODE_LISTEN_ERR			(-3005)
#define  RJONE_NET_MODE_INIT_ERR				(-3006)
#define  RJONE_NET_MAX_CLIENT_ERR				(-3007)
#define  RJONE_NET_READ_ERR					(-3008)
#define  RJONE_NET_IS_SVR_NOT_CLIENT_ERR		(-3009)
#define  RJONE_NET_NO_THIS_CLIENT_ERR			(-3010)
#define  RJONE_NET_READ_TIMEOUT_ERR			(-3011)
#define  RJONE_NET_SEND_ERR					(-3012)
#define  RJONE_NET_NOT_REGISTER_PUSH_SVR_ERR	(-3013)
#define  RJONE_NET_NOT_THIS_CLIENT_ERR		(-3014)



#define RJONE_NET_ERROR_PPPP_NOT_INITIALIZED					-4001
#define RJONE_NET_ERROR_PPPP_ALREADY_INITIALIZED				-4002
#define RJONE_NET_ERROR_PPPP_TIME_OUT							-4003
#define RJONE_NET_ERROR_PPPP_INVALID_ID						-4004
#define RJONE_NET_ERROR_PPPP_INVALID_PARAMETER				-4005
#define RJONE_NET_ERROR_PPPP_DEVICE_NOT_ONLINE				-4006
#define RJONE_NET_ERROR_PPPP_FAIL_TO_RESOLVE_NAME				-4007
#define RJONE_NET_ERROR_PPPP_INVALID_PREFIX					-4008
#define RJONE_NET_ERROR_PPPP_ID_OUT_OF_DATE					-4009
#define RJONE_NET_ERROR_PPPP_NO_RELAY_SERVER_AVAILABLE		-4010
#define RJONE_NET_ERROR_PPPP_INVALID_SESSION_HANDLE			-4011
#define RJONE_NET_ERROR_PPPP_SESSION_CLOSED_REMOTE			-4012
#define RJONE_NET_ERROR_PPPP_SESSION_CLOSED_TIMEOUT			-4013
#define RJONE_NET_ERROR_PPPP_SESSION_CLOSED_CALLED			-4014
#define RJONE_NET_ERROR_PPPP_REMOTE_SITE_BUFFER_FULL			-4015
#define RJONE_NET_ERROR_PPPP_USER_LISTEN_BREAK				-4016
#define RJONE_NET_ERROR_PPPP_MAX_SESSION						-4017
#define RJONE_NET_ERROR_PPPP_UDP_PORT_BIND_FAILED				-4018
#define RJONE_NET_ERROR_PPPP_USER_CONNECT_BREAK				-4019
#define RJONE_NET_ERROR_PPPP_SESSION_CLOSED_INSUFFICIENT_MEMORY	-4020
#define RJONE_NET_ERROR_PPPP_INVALID_APILICENSE				-4021
#define RJONE_NET_ERROR_PPPP_FAIL_TO_CREATE_THREAD			-4022


//ÍøÂçÐ­Òé´íÎó·µ»ØÖµ

#define  RJONE_NET_PASSWORD_NOT_RIGHT_ERR					(-5000)
#define  RJONE_NET_NOT_AUTHORIZE_ERR							(-5001)
#define  RJONE_NET_OTHER_USE_SPEAK_NOW_ERR					(-5002)
#define  RJONE_NET_NOT_HAVE_THIS_DEV_ERR						(-5003)
#define  RJONE_NET_OTHER_USE_UPGRADE_NOW_ERR				(-5004)
#define  RJONE_NET_PERPHERAL_DEV_ERR							(-5005)
#define  RJONE_NET_DEV_UPGRADE_NOT_ALLOW_LOGIN_ERR		(-5006)
#define  RJONE_NET_TOO_MUCH_USER_USE_VIDEO_ERR 				(-5007)



//Â¼Ïñ´íÎó·µ»ØÖµ
#define  RJONE_NET_NOT_HAVE_STORAGE_DEVICE_ERR				(-6000)
#define  RJONE_NET_BAD_STORAGE_DEVICE_ERR					(-6001)
#define  RJONE_NET_STORAGE_DEVICE_NOT_READY_ERR				(-6002)
#define  RJONE_NET_STORAGE_DEVICE_IS_FORMAT_NOW_ERR		(-6003)
#define  RJONE_NET_RECORD_FILE_LOG_BUF_IS_NOT_ENOUGH_ERR	(-6004)
#define  RJONE_NET_FILE_WRITE_ERR								(-6005)
#define  RJONE_NET_OPEN_PLAY_FILE_ERR							(-6006)


#ifdef __cplusplus
}
#endif

#endif 
