#ifndef     __IPCAM_WIFI_H__
#define     __IPCAM_WIFI_H__

#define IPCAM_WIFI_RETURN_VALUE  (-1000)
#define IPCAM_WIFI_NOT_FIND_SSID  IPCAM_WIFI_RETURN_VALUE+1
#define IPCAM_WIFI_NOT_SUPPORT_MODE  IPCAM_WIFI_RETURN_VALUE+2
#define IPCAM_WIFI_NOT_ALLOW_TEST  IPCAM_WIFI_RETURN_VALUE+3
#define IPCAM_WIFI_CONNECT_FAILED  IPCAM_WIFI_RETURN_VALUE+4

#endif