
include ../makefile.rule

INCLUDE += -I../../include
INCLUDE+=-I../avicodelib
INCLUDE+=-I../filesystem
INCLUDE += -I../common

LIBDIR=../../lib

USE_FILE = main.c testcom.c

EXEFILE = Hisi_9x16

LIBFILE = -lpthread
LIBFILE += -L$(LIBDIR) -lfilectrl -L$(LIBDIR) -lfdisk -L$(LIBDIR) -lfilesystem -L$(LIBDIR) -ldrvctrl



#all: $(EXEFILE)
#$(EXEFILE) : $(USE_FILE)

all:
	$(CC)  -o $(EXEFILE) $(USE_FILE) $(LIBFILE) $(INCLUDE) $(LIBS)
	cp $(EXEFILE) /nfs/yb

clean:
	rm -f  $(EXEFILE)

